  main = ".open-next/worker.js"
  name = "jenchan-biz"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat"]
  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"
  [r2_buckets]
  NEXT_INC_CACHE_R2_BUCKET=jen-bucket
  [browser]
  binding = "JEN_BROWSER"
  experimental_remote = true