
  [env.production]
  main = ".open-next/worker.js"
  name = "jenchan-biz"
  compatibility_date = "2025-03-25"
  compatibility_flags = ["nodejs_compat", "assets_navigation_prefers_asset_serving"]

  [assets]
  directory = ".open-next/assets"
  binding = "ASSETS"
  [r2_buckets]
  NEXT_INC_CACHE_R2_BUCKET=jen-bucket
  [browser]
  binding = "JEN_BROWSER"
  experimental_remote = true
  [observability]
  enabled = true

  [env.development]
    [services]
    WORKER_SELF_REFERENCE=jenchan-biz-development
    [r2_buckets]
    NEXT_INC_CACHE_R2_BUCKET=jen-preview-bucket