name: Deploy PRs to Cloudflare Preview
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      NODE_ENV: production
      CLOUDFLARE_PAGES: true
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NEXT_GOOGLE_ANALYTICS_ID: ${{ secrets.NEXT_GOOGLE_ANALYTICS_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          yarn install
          # Install OS build dependencies
          sudo apt-get update
          sudo apt-get install -y build-essential python3 g++ make

      - name: Build
        run: yarn run pages:build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: yarn
          command: pages deploy --project-name=jenchan-biz --branch=${{ github.ref_name }}
      - name: Print deployment-url
        run: echo ${{ steps.deploy.outputs.deployment-url }}
