name: Deploy to Cloudflare Pages
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          yarn install
          # Install OS build dependencies
          sudo apt-get update
          sudo apt-get install -y build-essential python3 g++ make

      - name: Build
        run: yarn run pages:build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '4.22.0'
          packageManager: yarn
          command: pages deploy
      - name: Print deployment-url
        run: echo ${{ steps.deploy.outputs.deployment-url }}
