name: Deploy to Cloudflare Pages
on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main
jobs:
  prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: '4.22.0'
          environment: production
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          packageManager: yarn
      - name: Build Pages
        run: yarn pages:build
      - name: Deploy Pages
        run: yarn deploy
      - name: Print deployment-url
        run: echo ${{ steps.deploy.outputs.deployment-url }}
